fixed indent error in yaml

diff --git a/.github/workflows/prod-request-merged.yml b/.github/workflows/prod-request-merged.yml
--- a/.github/workflows/prod-request-merged.yml
+++ b/.github/workflows/prod-request-merged.yml
@@ -25,25 +25,25 @@ jobs:
           echo "PR: ${GITHUB_REF}"
           echo "Branch: ${{ github.base_ref }}"
 
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - name: Save version type
-      # Whichever one return's true, will let their 'echo' statement run:
-      # Must wrap in "(*) || true" to prevent it from exiting on failure, until
-      #     'allow-failure' is finished getting added: https://github.com/actions/toolkit/issues/399
-      run: |
-        (${{ contains(github.event.pull_request.labels.*.name, 'patch') }} && echo "version_type=patch" >> $GITHUB_ENV) || true
-        (${{ contains(github.event.pull_request.labels.*.name, 'minor') }} && echo "version_type=minor" >> $GITHUB_ENV) || true
-        (${{ contains(github.event.pull_request.labels.*.name, 'major') }} && echo "version_type=major" >> $GITHUB_ENV) || true
+      - name: Save version type
+        # Whichever one return's true, will let their 'echo' statement run:
+        # Must wrap in "(*) || true" to prevent it from exiting on failure, until
+        #     'allow-failure' is finished getting added: https://github.com/actions/toolkit/issues/399
+        run: |
+          (${{ contains(github.event.pull_request.labels.*.name, 'patch') }} && echo "version_type=patch" >> $GITHUB_ENV) || true
+          (${{ contains(github.event.pull_request.labels.*.name, 'minor') }} && echo "version_type=minor" >> $GITHUB_ENV) || true
+          (${{ contains(github.event.pull_request.labels.*.name, 'major') }} && echo "version_type=major" >> $GITHUB_ENV) || true
 
-    - name: Create a Release
-      uses: zendesk/action-create-release@v1
-      env:
-        # NOT built in token, so this can trigger other actions:
-        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
-      with:
-        # version_type populated with the last job just above ^^
-        auto_increment_type: "${{ env.version_type }}"
-        tag_schema: semantic
-        draft: false
-        prerelease: false
+      - name: Create a Release
+        uses: zendesk/action-create-release@v1
+        env:
+          # NOT built in token, so this can trigger other actions:
+          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
+        with:
+          # version_type populated with the last job just above ^^
+          auto_increment_type: "${{ env.version_type }}"
+          tag_schema: semantic
+          draft: false
+          prerelease: false
